### ISSUE TITLE
doc - add a sample for external service

### ISSUE THREAD

**Issue by mborne** [mborne/ansible-traefik#1]
For example, `/etc/traefik/conf.d/jenkins.toml` : 

```toml
[http.services]
  [http.services.jenkins.loadBalancer]
    [[http.services.jenkins.loadBalancer.servers]]
      url = "http://127.0.0.1:8080/"


[http.routers.jenkins]
  rule = "Host(`jenkins.int.quadtreeworld.net`)"
  service = "jenkins@file"
```
